### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Logout timed out

### ISSUE THREAD

**Issue by MarcGodard** [canjs/can-zone#172]
Not sure when this started for me, I think it was after an npm upgrade.

The error doesn't seem to be preventing anything, but it is filling up logs.

```
admin@marcgodard:~/web/txbasewebsite.com/tx-base-website$ NODE_ENV=production PORT=8880 npm run start

> tx@0.1.0 start /home/admin/web/txbasewebsite.com/tx-base-website
> done-serve --port $PORT

Warning: done-serve is intended for development use only.
done-serve starting on http://localhost:8880
(node:28500) UnhandledPromiseRejectionWarning: Error: Logout timed out
    at Timeout.<anonymous> (file:/home/admin/web/txbasewebsite.com/tx-base-website/dist/bundles/tx/index.js:1:608293)
    at Timeout.<anonymous> (/home/admin/web/txbasewebsite.com/tx-base-website/node_modules/can-zone/lib/tasks.js:86:14)
    at Task.run (/home/admin/web/txbasewebsite.com/tx-base-website/node_modules/can-zone/lib/zone.js:38:17)
    at Zone.runTask (/home/admin/web/txbasewebsite.com/tx-base-website/node_modules/can-zone/lib/zone.js:180:14)
    at Timeout._onTimeout (/home/admin/web/txbasewebsite.com/tx-base-website/node_modules/can-zone/lib/zone.js:281:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:28500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:28500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

node version: 8.11.2
done-serve: ^2.0.0

Any idea what might be causing this?

**Comment by MarcGodard** [comment]
Will check it out next time I work on that. It is only when I run it on my server.

`Warning: done-serve is intended for development use only.`

that line puzzles me, how else can you run with SSR?

**Comment by matthewp** [comment]
Using done-ssr or done-ssr-middleware
